{% set name = "fastai" %}
{% set version = "2.7.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastai-{{ version }}.tar.gz
  sha256: c6b3a1766ac25afb0fb42143b2753189277ba31f8f8299ad7b92f234f0874585

build:
  entry_points:
    - configure_accelerate=fastai.distributed:configure_accelerate
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pip
    - packaging
    - fastdownload >=0.0.5,<2
    - fastcore >=1.4.5,<1.6
    - torchvision >=0.8.2
    - matplotlib-base
    - pandas
    - requests
    - pyyaml
    - fastprogress >=0.2.4
    - pillow >6.0.0
    - scikit-learn
    - scipy
    - spacy <4
    - pytorch >=1.7,<1.14

test:
  imports:
    - fastai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastai/fastai
  summary: fastai simplifies training fast and accurate neural nets using modern best practices
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
